-- AlterTable
ALTER TABLE "exercise_categories" ALTER COLUMN "create_date" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "update_date" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "target_areas" ALTER COLUMN "create_date" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "update_date" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "training_records" ADD COLUMN     "user_id" INTEGER,
ALTER COLUMN "create_date" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "update_date" SET DEFAULT CURRENT_TIMESTAMP;
